networks:
  frontend:
  backend: 
services:
  catalog:
    image: events/catalogapi
    build: 
      context: ./EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source = mssqlserver; Initial Catalog = EventDb; User Id=sa; Password=EventApi123(!); Connect Timeout = 30; Encrypt = False; Trust Server Certificate=False;"
      ExternalBaseurl: "http://localhost:7000"
      ASPNETCORE_HTTP_PORTS: 80
    ports: 
      - "7000:80"
      - "7001:443"
    container_name: eventscatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  tokenserver:
    image: events/tokenapi
    build:
      context: ./TokenServiceAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source = tokensqlserver; Initial Catalog = ToeknServiceDb; User Id=sa;Password=TokenApi123(!); Connect Timeout = 30; Encrypt = False; Trust Server Certificate=False;"
      ASPNETCORE_ENVIRONMENT: Development
      Mvc: http://localhost:7520
      ASPNETCORE_HTTP_PORTS: 80
    ports:
      - "7010:80"
    container_name: eventstokenapi
    networks:
      - frontend
      - backend
    depends_on:
      - tokensqlserver
  
  webmvc:
    image: events/webmvc
    build:
      context: ./WebMVC
      dockerfile: Dockerfile
    environment:
      EventUrl: http://catalog
      IdentityUrl: http://192.168.0.28:7010
      CallbackUrl: http://localhost:7520
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 80
    ports:
      - "7520:80"
    container_name: webshop
    networks:
      - frontend
    depends_on:
      - catalog


  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment: 
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: EventApi123(!)
    ports:
      - "1448:1433" 
    container_name: eventscatalogsqlserver
    networks:
      - backend

  tokensqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: TokenApi123(!)
    ports:
      - "1449:1433"
    container_name: jewelstokensqlserver
    networks:
      - backend